# Generated by Django 2.2.2 on 2019-07-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20190703_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, upload_to='')),
                ('public', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('alfa', 'Альфа версия'), ('beta', 'Бета версия'), ('green', 'Продакшн')], default='alfa', max_length=50)),
                ('priority', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='status',
            field=models.CharField(choices=[('alfa', 'Альфа версия'), ('beta', 'Бета версия'), ('green', 'Продакшн')], default='alfa', max_length=50),
        ),
    ]
