# Generated by Django 2.2.2 on 2019-07-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20190704_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='source_db',
            field=models.CharField(choices=[('dwh', 'DWH Producation'), ('dwh-test', 'DWH Testing')], default='dwh', max_length=50),
        ),
    ]
